### ISSUE TITLE
请问下目前支持中文吗？

### ISSUE THREAD

**Issue by Kerry0123** [THUDM/WebGLM#1]
目前模型是指支持英文吗，我用中文测试，发现报错：

**Comment by Kerry0123** [comment]
报错结果如下：
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by Longin-Yu** [comment]
对，这个版本目前只支持英文

**Comment by Kerry0123** [comment]
在推理和模型训练的代码中，没看到scoer部分，辛苦指导一下

**Comment by Kerry0123** [comment]
> 英文

后续会有计划开放中文吗

**Comment by Longin-Yu** [comment]
> 在推理和模型训练的代码中，没看到scoer部分，辛苦指导一下

感谢关注和提问！我们在该版本中没有加入 scorer 的原因是简化部署和提高效率，以便快速开始使用我们的模型。但我们会在未来的版本更新中考虑提供一个 scorer 的选项（部署模型时，可以选择是否采用 scorer）。

**Comment by Longin-Yu** [comment]
> 后续会有计划开放中文吗

是的，欢迎持续关注！我们更新后会在 Readme 中同步。

**Comment by Kerry0123** [comment]
收到，感谢回答！
