### ISSUE TITLE
Unable to Download Retriever-Pretrained-Checkpoint or Training Data

### ISSUE THREAD

**Issue by alvis233** [THUDM/WebGLM#13]
Hi, I am attempting to replicate the remarkable achievement, but it appears that everything on Tsinghua Cloud has expired. I am unable to download the pre-trained checkpoint by simply clicking the URL in README.md or using the download.py script, nor can I access the training data. Can anyone help me? I would greatly appreciate it.

**Comment by Xiao9905** [comment]
@alvis233 Hi,

Thanks for your interest in WebGLM. We are sorry that the cloud storage is experiencing a migration this morning, and it will soon be available. We will inform you once it is ready.

**Comment by Xiao9905** [comment]
@alvis233 

The download is up now.
