### ISSUE TITLE
请问scorer怎么影响generator？

### ISSUE THREAD

**Issue by BboyIcee** [THUDM/WebGLM#15]
generator训练得时候能学习到score的信号吗？这个信号对生成应该也是很重要的吧。

**Comment by Longin-Yu** [comment]
目前 Generator 在训练时没有使用 Scorer 的信号，而是直接使用来自生成数据的监督信号。不过将 Scorer 的信号融入进 Generator 训练的过程是一个很有意思的话题，值得更进一步的研究。
