### ISSUE TITLE
基于人类偏好的打分器是指Rouge么？

### ISSUE THREAD

**Issue by shishi11** [THUDM/WebGLM#17]

**Comment by Longin-Yu** [comment]
Rouge 是语言模型生成评价的一种指标，我们用这个指标生成了训练 Retriever 的数据。基于人类偏好的打分器中没有使用这个指标，而是通过开放数据监督训练得到的。

**Comment by shishi11** [comment]
大概明白了，主要看DBUTILS代码时的疑惑。还得看看论文。咱们这里没有模型训练的细节代码吧。
