### ISSUE TITLE
下载检索器权重的时候报错

### ISSUE THREAD

**Issue by SoloPro-Git** [THUDM/WebGLM#22]
执行python download.py retriever-pretrained-checkpoint的时候 @Longin-Yu 
![image](https://github.com/THUDM/WebGLM/assets/57442574/70dd3958-d743-4836-b7f6-74a39ec0e7ad)
![image](https://github.com/THUDM/WebGLM/assets/57442574/f4389657-e209-432c-ae41-c60e740a8f57)
![image](https://github.com/THUDM/WebGLM/assets/57442574/486eb923-0123-4b68-aeb6-b41d92dbcc29)
默认是 / 但是网页返回没有这个目录

**Comment by SoloPro-Git** [comment]
中文的readme有问题,英文的就没有问题了

**Comment by LinXin04** [comment]
怎么解决的呢？现在无法下载
