### ISSUE TITLE
怎么在代码改变上面的url里的ip地址

### ISSUE THREAD

**Issue by Mrgengli** [THUDM/WebGLM#29]
![捕获](https://github.com/THUDM/WebGLM/assets/114299344/b1d97bd3-49dc-4f4e-967c-3a0c652597e3)
怎么在代码改变上面的url里的ip地址

**Comment by Longin-Yu** [comment]
这个 IP 地址是 localhost，如果你想在另外的 IP 部署，请在 launch 中设置 server_name 参数。关于 localhost，你可以参考 https://baike.baidu.com/item/localhost/2608730。
