### ISSUE TITLE
Cannot generate a public link

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [THUDM/WebGLM#30]
When I followed the prompt to add ‘share=True’ in web_demo.py, I still received no response.

**Comment by Longin-Yu** [comment]
Usually, if you don't need to open public links, localhost is enough. 
If you want, you can refer to the issue of the [gradio](https://github.com/gradio-app/gradio/issues/3498) repository.

**Comment by Lowlowlowlowlowlow** [comment]
> 

I first downgraded gradio to version 3.9 
`pip install gradio==3.9`
and then In `web_demo.py`, I changed line 65 from:
```python
with gr.Blocks(theme=gr.themes.Base(), css=CSS) as demo:
```
复制
to:
```python
with gr.Blocks(css=CSS) as demo:
```
