### ISSUE TITLE
Hello, do you plan to open source the WebGLM-QA dataset?

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [THUDM/WebGLM#42]
Or can you give a hint to structure this dataset?

**Comment by Xiao9905** [comment]
@Lowlowlowlowlowlow Hi,

Thanks for your interest in WebGLM! The WebGLM-QA dataset was open-sourced at the very beginning. Please see: https://github.com/THUDM/WebGLM/tree/main#prepare-data-webglm-qa
