### ISSUE TITLE
web_demo 搜索后无法得到结果

### ISSUE THREAD

**Issue by cryptokeenz** [THUDM/WebGLM#44]
环境、模型、训练权重数据都安装好了，但搜索后一直加载，不显示结果数据，大佬可以看看什么情况吗

![image](https://github.com/THUDM/WebGLM/assets/108882370/f8f848cc-b69b-4c62-8fe0-0afcc2b33825)

**Comment by Longin-Yu** [comment]
感谢尝试WebGLM！可以展示一下运行时的控制台（终端）截图吗？

**Comment by cryptokeenz** [comment]
感谢回复！终端没有信息显示，是不是我哪里配置有问题···

![image](https://github.com/THUDM/WebGLM/assets/108882370/7360a168-2530-45c1-a605-3f0447204321)

**Comment by eu09** [comment]
WebGLM Initializing...
WebGLM Loaded
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='2cm28lzpd8w_0' coro=<Queue.process_events() done, defined at /home/elohlinux/WebGLM/venv/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['hello'], 'even...on_hash': '2cm28lzpd8w'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing>
Traceback (most recent call last):
  File "/home/elohlinux/WebGLM/venv/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/elohlinux/WebGLM/venv/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/elohlinux/WebGLM/venv/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/home/elohlinux/WebGLM/venv/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['hello'], 'even...on_hash': '2cm28lzpd8w'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing

當我刷新頁面並輸入空字符串並輸入時，它會報告此消息

**Comment by cryptokeenz** [comment]
> @cryptokeenz upgrade gradio==3.38.0 , it work .

Oh my god, I'm up and running now, thank you so much!
