### ISSUE TITLE
能不能别用那个SerpAPI密

### ISSUE THREAD

**Issue by liaoweiguo** [THUDM/WebGLM#9]
要翻墙就没法用了

**Comment by lhtpluto** [comment]
是呢   求开源使用用国内可用搜索API的

**Comment by Longin-Yu** [comment]
感谢建议！我们在最新版中加入了 Bing Search，启动 WebGLM 时，可以通过 --searcher bing 使用 Bing Search！

**Comment by lhtpluto** [comment]
> 感谢建议！我们在最新版中加入了 Bing Search，启动 WebGLM 时，可以通过 --searcher bing 使用 Bing Search！

响应超及时，点赞
